version: '2'
services:
  front_end:
    build: .
    environment:
      NODE_ENV: 'development'
      API_HOST: 'api'
      API_PORT: 8080
    ports:
      - "3000:3000"
    expose:
      - 3000
    volumes:
      - ./app:/usr/src/app/app
