export const CHARACTER_INDEX_FETCH_REQUEST = 'CHARACTER_INDEX_FETCH_REQUEST'
export const CHARACTER_INDEX_FETCH_SUCCESS = 'CHARACTER_INDEX_FETCH_SUCCESS'
export const CHARACTER_INDEX_FETCH_FAILURE = 'CHARACTER_INDEX_FETCH_FAILURE'
export const CHARACTER_SELECT = 'CHARACTER_SELECT'
export const CHARACTER_DESELECT = 'CHARACTER_DESELECT'
export const CHARACTER_SEARCH_UPDATE = 'CHARACTER_SEARCH_UPDATE'
export const CHARACTER_SEARCH_CLEAR = 'CHARACTER_SEARCH_CLEAR'

